before:
  hooks:
    - go mod download
builds:
- main: ./cmd/prana/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- github:
    owner: phogolabs
    name: homebrew-tap
  name: prana
  description: Golang Database Management and Code Generation
  homepage: https://github.com/phogolabs/prana
  test: |
   system "#{bin}/prana -v"
