language: go
go:
  - 1.12.3

services:
  - postgresql
  - mysql

addons:
  postgresql: "9.4"

before_script:
  - mysql -e 'CREATE DATABASE prana;'
  - psql -c 'CREATE DATABASE prana;' -U postgres

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - export GO111MODULE=on
  - export CGO_ENABLED=0
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get github.com/mattn/goveralls
  - go install github.com/onsi/ginkgo/ginkgo
  - go mod download
  - go mod verify

script:
  - ginkgo -r -v -covermode=atomic

after_success:
  - script/cover.sh
  - bash <(curl -s https://codecov.io/bash)
