// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"

	"github.com/phogolabs/prana/sqlmigr"
)

type MigrationProvider struct {
	DeleteStub        func(*sqlmigr.Migration) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 *sqlmigr.Migration
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	ExistsStub        func(*sqlmigr.Migration) bool
	existsMutex       sync.RWMutex
	existsArgsForCall []struct {
		arg1 *sqlmigr.Migration
	}
	existsReturns struct {
		result1 bool
	}
	existsReturnsOnCall map[int]struct {
		result1 bool
	}
	InsertStub        func(*sqlmigr.Migration) error
	insertMutex       sync.RWMutex
	insertArgsForCall []struct {
		arg1 *sqlmigr.Migration
	}
	insertReturns struct {
		result1 error
	}
	insertReturnsOnCall map[int]struct {
		result1 error
	}
	MigrationsStub        func() ([]*sqlmigr.Migration, error)
	migrationsMutex       sync.RWMutex
	migrationsArgsForCall []struct {
	}
	migrationsReturns struct {
		result1 []*sqlmigr.Migration
		result2 error
	}
	migrationsReturnsOnCall map[int]struct {
		result1 []*sqlmigr.Migration
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *MigrationProvider) Delete(arg1 *sqlmigr.Migration) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 *sqlmigr.Migration
	}{arg1})
	fake.recordInvocation("Delete", []interface{}{arg1})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteReturns
	return fakeReturns.result1
}

func (fake *MigrationProvider) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *MigrationProvider) DeleteCalls(stub func(*sqlmigr.Migration) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *MigrationProvider) DeleteArgsForCall(i int) *sqlmigr.Migration {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MigrationProvider) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *MigrationProvider) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MigrationProvider) Exists(arg1 *sqlmigr.Migration) bool {
	fake.existsMutex.Lock()
	ret, specificReturn := fake.existsReturnsOnCall[len(fake.existsArgsForCall)]
	fake.existsArgsForCall = append(fake.existsArgsForCall, struct {
		arg1 *sqlmigr.Migration
	}{arg1})
	fake.recordInvocation("Exists", []interface{}{arg1})
	fake.existsMutex.Unlock()
	if fake.ExistsStub != nil {
		return fake.ExistsStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.existsReturns
	return fakeReturns.result1
}

func (fake *MigrationProvider) ExistsCallCount() int {
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	return len(fake.existsArgsForCall)
}

func (fake *MigrationProvider) ExistsCalls(stub func(*sqlmigr.Migration) bool) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = stub
}

func (fake *MigrationProvider) ExistsArgsForCall(i int) *sqlmigr.Migration {
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	argsForCall := fake.existsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MigrationProvider) ExistsReturns(result1 bool) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = nil
	fake.existsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *MigrationProvider) ExistsReturnsOnCall(i int, result1 bool) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = nil
	if fake.existsReturnsOnCall == nil {
		fake.existsReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.existsReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *MigrationProvider) Insert(arg1 *sqlmigr.Migration) error {
	fake.insertMutex.Lock()
	ret, specificReturn := fake.insertReturnsOnCall[len(fake.insertArgsForCall)]
	fake.insertArgsForCall = append(fake.insertArgsForCall, struct {
		arg1 *sqlmigr.Migration
	}{arg1})
	fake.recordInvocation("Insert", []interface{}{arg1})
	fake.insertMutex.Unlock()
	if fake.InsertStub != nil {
		return fake.InsertStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.insertReturns
	return fakeReturns.result1
}

func (fake *MigrationProvider) InsertCallCount() int {
	fake.insertMutex.RLock()
	defer fake.insertMutex.RUnlock()
	return len(fake.insertArgsForCall)
}

func (fake *MigrationProvider) InsertCalls(stub func(*sqlmigr.Migration) error) {
	fake.insertMutex.Lock()
	defer fake.insertMutex.Unlock()
	fake.InsertStub = stub
}

func (fake *MigrationProvider) InsertArgsForCall(i int) *sqlmigr.Migration {
	fake.insertMutex.RLock()
	defer fake.insertMutex.RUnlock()
	argsForCall := fake.insertArgsForCall[i]
	return argsForCall.arg1
}

func (fake *MigrationProvider) InsertReturns(result1 error) {
	fake.insertMutex.Lock()
	defer fake.insertMutex.Unlock()
	fake.InsertStub = nil
	fake.insertReturns = struct {
		result1 error
	}{result1}
}

func (fake *MigrationProvider) InsertReturnsOnCall(i int, result1 error) {
	fake.insertMutex.Lock()
	defer fake.insertMutex.Unlock()
	fake.InsertStub = nil
	if fake.insertReturnsOnCall == nil {
		fake.insertReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.insertReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *MigrationProvider) Migrations() ([]*sqlmigr.Migration, error) {
	fake.migrationsMutex.Lock()
	ret, specificReturn := fake.migrationsReturnsOnCall[len(fake.migrationsArgsForCall)]
	fake.migrationsArgsForCall = append(fake.migrationsArgsForCall, struct {
	}{})
	fake.recordInvocation("Migrations", []interface{}{})
	fake.migrationsMutex.Unlock()
	if fake.MigrationsStub != nil {
		return fake.MigrationsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.migrationsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *MigrationProvider) MigrationsCallCount() int {
	fake.migrationsMutex.RLock()
	defer fake.migrationsMutex.RUnlock()
	return len(fake.migrationsArgsForCall)
}

func (fake *MigrationProvider) MigrationsCalls(stub func() ([]*sqlmigr.Migration, error)) {
	fake.migrationsMutex.Lock()
	defer fake.migrationsMutex.Unlock()
	fake.MigrationsStub = stub
}

func (fake *MigrationProvider) MigrationsReturns(result1 []*sqlmigr.Migration, result2 error) {
	fake.migrationsMutex.Lock()
	defer fake.migrationsMutex.Unlock()
	fake.MigrationsStub = nil
	fake.migrationsReturns = struct {
		result1 []*sqlmigr.Migration
		result2 error
	}{result1, result2}
}

func (fake *MigrationProvider) MigrationsReturnsOnCall(i int, result1 []*sqlmigr.Migration, result2 error) {
	fake.migrationsMutex.Lock()
	defer fake.migrationsMutex.Unlock()
	fake.MigrationsStub = nil
	if fake.migrationsReturnsOnCall == nil {
		fake.migrationsReturnsOnCall = make(map[int]struct {
			result1 []*sqlmigr.Migration
			result2 error
		})
	}
	fake.migrationsReturnsOnCall[i] = struct {
		result1 []*sqlmigr.Migration
		result2 error
	}{result1, result2}
}

func (fake *MigrationProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	fake.insertMutex.RLock()
	defer fake.insertMutex.RUnlock()
	fake.migrationsMutex.RLock()
	defer fake.migrationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *MigrationProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sqlmigr.MigrationProvider = new(MigrationProvider)
