// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"

	"github.com/phogolabs/prana/sqlmodel"
)

type SchemaProvider struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	SchemaStub        func(string, ...string) (*sqlmodel.Schema, error)
	schemaMutex       sync.RWMutex
	schemaArgsForCall []struct {
		arg1 string
		arg2 []string
	}
	schemaReturns struct {
		result1 *sqlmodel.Schema
		result2 error
	}
	schemaReturnsOnCall map[int]struct {
		result1 *sqlmodel.Schema
		result2 error
	}
	TablesStub        func(string) ([]string, error)
	tablesMutex       sync.RWMutex
	tablesArgsForCall []struct {
		arg1 string
	}
	tablesReturns struct {
		result1 []string
		result2 error
	}
	tablesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *SchemaProvider) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if fake.CloseStub != nil {
		return fake.CloseStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.closeReturns
	return fakeReturns.result1
}

func (fake *SchemaProvider) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *SchemaProvider) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *SchemaProvider) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *SchemaProvider) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *SchemaProvider) Schema(arg1 string, arg2 ...string) (*sqlmodel.Schema, error) {
	fake.schemaMutex.Lock()
	ret, specificReturn := fake.schemaReturnsOnCall[len(fake.schemaArgsForCall)]
	fake.schemaArgsForCall = append(fake.schemaArgsForCall, struct {
		arg1 string
		arg2 []string
	}{arg1, arg2})
	fake.recordInvocation("Schema", []interface{}{arg1, arg2})
	fake.schemaMutex.Unlock()
	if fake.SchemaStub != nil {
		return fake.SchemaStub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.schemaReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *SchemaProvider) SchemaCallCount() int {
	fake.schemaMutex.RLock()
	defer fake.schemaMutex.RUnlock()
	return len(fake.schemaArgsForCall)
}

func (fake *SchemaProvider) SchemaCalls(stub func(string, ...string) (*sqlmodel.Schema, error)) {
	fake.schemaMutex.Lock()
	defer fake.schemaMutex.Unlock()
	fake.SchemaStub = stub
}

func (fake *SchemaProvider) SchemaArgsForCall(i int) (string, []string) {
	fake.schemaMutex.RLock()
	defer fake.schemaMutex.RUnlock()
	argsForCall := fake.schemaArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *SchemaProvider) SchemaReturns(result1 *sqlmodel.Schema, result2 error) {
	fake.schemaMutex.Lock()
	defer fake.schemaMutex.Unlock()
	fake.SchemaStub = nil
	fake.schemaReturns = struct {
		result1 *sqlmodel.Schema
		result2 error
	}{result1, result2}
}

func (fake *SchemaProvider) SchemaReturnsOnCall(i int, result1 *sqlmodel.Schema, result2 error) {
	fake.schemaMutex.Lock()
	defer fake.schemaMutex.Unlock()
	fake.SchemaStub = nil
	if fake.schemaReturnsOnCall == nil {
		fake.schemaReturnsOnCall = make(map[int]struct {
			result1 *sqlmodel.Schema
			result2 error
		})
	}
	fake.schemaReturnsOnCall[i] = struct {
		result1 *sqlmodel.Schema
		result2 error
	}{result1, result2}
}

func (fake *SchemaProvider) Tables(arg1 string) ([]string, error) {
	fake.tablesMutex.Lock()
	ret, specificReturn := fake.tablesReturnsOnCall[len(fake.tablesArgsForCall)]
	fake.tablesArgsForCall = append(fake.tablesArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("Tables", []interface{}{arg1})
	fake.tablesMutex.Unlock()
	if fake.TablesStub != nil {
		return fake.TablesStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.tablesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *SchemaProvider) TablesCallCount() int {
	fake.tablesMutex.RLock()
	defer fake.tablesMutex.RUnlock()
	return len(fake.tablesArgsForCall)
}

func (fake *SchemaProvider) TablesCalls(stub func(string) ([]string, error)) {
	fake.tablesMutex.Lock()
	defer fake.tablesMutex.Unlock()
	fake.TablesStub = stub
}

func (fake *SchemaProvider) TablesArgsForCall(i int) string {
	fake.tablesMutex.RLock()
	defer fake.tablesMutex.RUnlock()
	argsForCall := fake.tablesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *SchemaProvider) TablesReturns(result1 []string, result2 error) {
	fake.tablesMutex.Lock()
	defer fake.tablesMutex.Unlock()
	fake.TablesStub = nil
	fake.tablesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *SchemaProvider) TablesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.tablesMutex.Lock()
	defer fake.tablesMutex.Unlock()
	fake.TablesStub = nil
	if fake.tablesReturnsOnCall == nil {
		fake.tablesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.tablesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *SchemaProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.schemaMutex.RLock()
	defer fake.schemaMutex.RUnlock()
	fake.tablesMutex.RLock()
	defer fake.tablesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *SchemaProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ sqlmodel.SchemaProvider = new(SchemaProvider)
