name: release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v1

      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.x'

      - name: Release Application
        uses: goreleaser/goreleaser-action@v2.8.0
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASE_GITHUB_TOKEN }}
